FROM node:20 AS build

WORKDIR /app
COPY ./webpage/package*.json ./
RUN npm install
COPY ./webpage ./
RUN ls -la ./
RUN npm run build

FROM nginxinc/nginx-unprivileged:alpine-slim
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/entrypoint-web.sh /entrypoint.sh
EXPOSE 8237

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]