services:
  automikan-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile-web
    image: automikan-web
    container_name: automikan-web
    environment:
      - API_BASE_URL="http://automikan-server:8236"
    ports:
      - 8237:8237
    networks:
      - automikan
    restart: unless-stopped

networks:
  automikan:
    external: true